name: Deploy Talk (external)
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Enter the tag to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Release to ~doznec-dozzod-marzod (external)"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release
        with:
          app: 'talk'
          ship: 'external'
          credentials: ${{ secrets.JANEWAY_SERVICE_KEY }}
          ssh-sec-key: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          ssh-pub-key: ${{ secrets.JANEWAY_SSH_PUB_KEY }}
          ref: ${{ github.event.inputs.tag }}